plugins {
    id 'java'
    id 'org.springframework.boot' version '3.2.5' // 또는 최신 버전
    id 'io.spring.dependency-management' version '1.1.4'
}

group = 'com.ll'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {

    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-web'

    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

    runtimeOnly 'com.mysql:mysql-connector-j'

}

test {
    useJUnitPlatform()
}